### ISSUE TITLE
Beadandó

### ISSUE THREAD

**Issue by LuxuryAgency** [Teaching-projects/januari-beadando-LuxuryAgency#1]
Szép Napot Tanár Úr!
Leadtam feladatomat.

**Comment by hegyhati** [comment]
Negyes meglesz ez, de:
 - a matekot az if-nel nem ertem, miert 5*a*b? Az hogy jon ki?
 - osszegx helyett szerintem tudsz jobb valtozoneveket is kitalalni
 - a vegen csinalsz `_`-al egy for ciklust, amit akkor hasznalunk, amikor a ciklusmagban NEM akarjuk hasznalni azt, hogy hanyadik iteracioban vagyunk. Majd csinalsz ket teljesen redundans valtozot, amikkel szamon tartod, hogy hanyadik ciklusban vagy. Szoval ez most kicsit olyan, mintha lenne egy kapad, eldobod, majd megfogsz ket gereblyet egyszerre, es azzal pufolod a foldet. Mukodik, de miert nem hasznalod a kapat, es dobod el a gereblyeket?

Ezeket azert pufold helyre rajta.

Az otoshoz tessek pl a meret alapjan a feluletet visszaado fuggvenyt kiszervezni fuggvenybe.

**Comment by LuxuryAgency** [comment]
Kipofoztam a programot Tanár Úr és visszatöltöttem!

**Comment by hegyhati** [comment]
A matekot az 2 szamos esetben tovabbra sem ertem, de a tobbi atszervezes rendben. 

Igy negyes, otoshoz tovabrba is a fuggvenyesdi kellene.

**Comment by LuxuryAgency** [comment]
Defeltem és visszatöltöttem Tanár Úr!

**Comment by hegyhati** [comment]
Am legyen, 5.
